<a href="https://colab.research.google.com/github/Aakash-777/Insurance-Premium-Prediction/blob/main/Insurance_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("insurance.csv")
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
print(x,"\n\n")
print(y)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.8 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.9 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.1 0 'yes' 'northwest']] 


[16884.92  1725.55  4449.46 ...  1629.83  2007.95 29141.36]


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,4,5])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)
print(x[0])

[[1.0 0.0 1.0 ... 19 27.9 0]
 [0.0 1.0 1.0 ... 18 33.8 1]
 [0.0 1.0 1.0 ... 28 33.0 3]
 ...
 [1.0 0.0 1.0 ... 18 36.9 0]
 [1.0 0.0 1.0 ... 21 25.8 0]
 [1.0 0.0 1.0 ... 61 29.1 0]]
[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 19 27.9 0]


In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)
print(x_train,x_test,y_train,y_test,sep="\n\n")

[[0.0 1.0 1.0 ... 42 30.0 0]
 [0.0 1.0 1.0 ... 34 30.8 0]
 [0.0 1.0 1.0 ... 42 24.6 0]
 ...
 [0.0 1.0 1.0 ... 40 25.1 0]
 [0.0 1.0 1.0 ... 19 35.5 0]
 [1.0 0.0 1.0 ... 33 18.5 1]]

[[0.0 1.0 1.0 ... 52 30.2 1]
 [1.0 0.0 1.0 ... 47 29.4 1]
 [0.0 1.0 1.0 ... 48 40.6 2]
 ...
 [0.0 1.0 1.0 ... 18 33.8 1]
 [1.0 0.0 1.0 ... 38 30.7 1]
 [0.0 1.0 0.0 ... 51 22.4 0]]

[22144.03 35491.64 19515.54 ...  5415.66  1646.43  4766.02]

[ 9724.53  8547.69 45702.02 12950.07  9644.25  4500.34  2198.19 11436.74
  7537.16  5425.02  6753.04 10493.95  7337.75  4185.1  18310.74 10702.64
 12523.6   3490.55  6457.84 33475.82 23967.38 12643.38 23045.57 23065.42
  1674.63  4667.61  3732.63  7682.67  3756.62  8413.46  8059.68 48970.25
 12979.36 20630.28 14571.89  4137.52  8347.16 51194.56 40003.33  1880.49
  5458.05  2867.12 20149.32 47496.49 36149.48 26018.95 19749.38  6940.91
  4718.2  22192.44  2899.49 18838.7  23568.27 46255.11 24227.34  3268.85
  2322.62  8827.21 14478.33 13112.6   1253.94 46718.16 13919.82  9

In [9]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [11]:
y_pred=regressor.predict(x_test)
print(y_pred)

[11288.  9224. 38284. 16384.  6752.  4460.  1552. 14100.  8788.  7780.
  4564. 10056.  8448.  3564. 28116. 10492. 11512.  6524.  8504. 27524.
 33872. 14056. 11640. 31808.  4364.  9612.  1128.  9540.  3520. 10664.
  8800. 40108. 15720. 13920. 24732.  5104. 12772. 30820. 33248.  3296.
  4000.  4204. 30916. 39632. 27464.  4860. 10364.  8076.  3592.  9980.
  5628.  3240. 33120. 38340. 15636.  7524.  5896.  9676.  9216. 11964.
  2012. 39100. 15088. 11924. 14456. 13608. 26020. 32420.   660. 10440.
 11984. 11724. 25364. 15264. 10956. 12580.  6736.  9808. 30136. 39120.
 11964. 36820.  4472.  9524. 35192. 29080.  8244.  5152. 12172. 30512.
  9980. 11496.  8228.  8648.  8812.  7244. 36364. 33288.  7416. 15152.
  4224.  9016.  6060. 31652. 33200.  1804.  9196.  6408. 14936. 37268.
  9980. 10696.  9980. 27344. 39932.  8924.   524.  9152. 15316.  9800.
 35304.  7068. 16504. 10044.  7912.  2788. 32828. 31736. 39592.  5792.
  9052.  3808.  7376.  9080.]


In [12]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print("R squared error : ",r2)

R squared error :  0.8211231121023425
